server:
  port: 8080

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
      fail-fast: true
    gateway:
      metrics:
        enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/delivery/**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
          - metrics