version: '3.8'

services:
  q-pang-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  q-pang-config-server:
    build: ./config-server
    ports:
      - 8888:8888
    restart: on-failure
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - q-pang-db

  q-pang-discovery-server:
    build: ./discovery-server
    ports:
      - 8761:8761
    restart: on-failure
    depends_on:
      - q-pang-db

  q-pang-gateway-server:
    build: ./gateway-server
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://q-pang-config-server:8888"
      DISCOVERY_SERVER_URI: "http://q-pang-discovery-server:8761/eureka/"
      JWT_SECRET: "dongkyun-jwt-secret"
    depends_on:
      - q-pang-db
      - q-pang-config-server
      - q-pang-discovery-server

  q-pang-user-service:
    build: ./user-service
    ports:
      - 8081:8080
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://q-pang-config-server:8888"
      DISCOVERY_SERVER_URI: "http://q-pang-discovery-server:8761/eureka/"
      USER_DB_CONNECTION_URI: "jdbc:mysql://q-pang-db:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      JWT_SECRET: "dongkyun-jwt-secret"
      VALIDITY_IN_MILLISECONDS: 36000000
    depends_on:
      - q-pang-db
      - q-pang-config-server
      - q-pang-discovery-server
      - q-pang-gateway-server

  q-pang-product-service:
    build: ./product-service
    ports:
      - 8082:8080
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://q-pang-config-server:8888"
      DISCOVERY_SERVER_URI: "http://q-pang-discovery-server:8761/eureka/"
      PRODUCT_DB_CONNECTION_URI: "jdbc:mysql://q-pang-db:3306/product?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    depends_on:
      - q-pang-db
      - q-pang-config-server
      - q-pang-discovery-server
      - q-pang-gateway-server

  q-pang-order-service:
    build: ./order-service
    ports:
      - 8083:8080
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://q-pang-config-server:8888"
      DISCOVERY_SERVER_URI: "http://q-pang-discovery-server:8761/eureka/"
      ORDER_DB_CONNECTION_URI: "jdbc:mysql://q-pang-db:3306/order?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    depends_on:
      - q-pang-db
      - q-pang-config-server
      - q-pang-discovery-server
      - q-pang-gateway-server

  q-pang-delivery-service:
    build: ./delivery-service
    ports:
      - 8084:8080
    restart: on-failure
    environment:
      CONFIG_SERVER_URI: "http://q-pang-config-server:8888"
      DISCOVERY_SERVER_URI: "http://q-pang-discovery-server:8761/eureka/"
      DELIVERY_DB_CONNECTION_URI: "jdbc:mysql://q-pang-db:3306/delivery?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    depends_on:
      - q-pang-db
      - q-pang-config-server
      - q-pang-discovery-server
      - q-pang-gateway-server