server:
  port: 8080

spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
      fail-fast: true
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh