server:
  port: 8888

spring:
  profiles:
    active:
      - native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/