spring:
  datasource:
    url: ${ORDER_DB_CONNECTION_URI:jdbc:mysql://localhost:3306/order?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}