spring:
  datasource:
    url: ${PRODUCT_DB_CONNECTION_URI:jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh