spring:
  datasource:
    url: ${USER_DB_CONNECTION_URI:jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info