spring:
  datasource:
    url: ${USER_DB_CONNECTION_URI:jdbc:mysql://localhost:3306/user?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URI:http://localhost:8761/eureka/}

jwt:
  validity-in-milliseconds: ${VALIDITY_IN_MILLISECONDS:216000000}